// <auto-generated />
namespace Movie_codefirstproject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class codefirst : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(codefirst));
        
        string IMigrationMetadata.Id
        {
            get { return "202211211508062_codefirst"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
